// The file contents for the current environment will overwrite these during build.
// The build system defaults to the dev environment which uses `environment.ts`, but if you do
// `ng build --env=prod` then `environment.prod.ts` will be used instead.
// The list of which env maps to which file can be found in `.angular-cli.json`.

// `.env.ts` is generated by the `npm run env` command
import env from './.env';

export const environment = {
  production: false,
  version: env.npm_package_version + '-dev',
    
  basePath : 'https://api.alindrelays.com/alindsalesapp/',
  serverUrl: 'https://api.alindrelays.com/alindsalesapp/',
  /* basePath : 'http://97.74.85.211:8080/alindsalesapp/',
  serverUrl: 'http://97.74.85.211:8080/alindsalesapp/',
  *//*  basePath : 'http://97.74.85.211:8080/dev-alindsales/',
  serverUrl: 'http://97.74.85.211:8080/dev-alindsales/',
  */ // basePath : 'http://97.74.85.211:8080/',
  //serverUrl: 'http://97.74.85.211:8080/',
  defaultLanguage: 'en-US',
  supportedLanguages: [
    'en-US',
    'fr-FR'
  ]
};
